# Generated by Django 3.0.5 on 2021-05-11 04:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0002_pull_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merged_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('from_branch', models.CharField(max_length=100)),
                ('to_branch', models.CharField(max_length=100)),
                ('time_stamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
